In [ ]:
# Lab01

In [1]:
import numpy as np
import pandas as pd

In [2]:
dados_marketing = pd.read_csv(r"C:\Users\enggi\Workspace\ALGORITMOS_IA\CURSO_IA\ADEC_ANALISE_DADOS_BALBINOT\DADOS\Marketing01.csv")

In [3]:
dados_marketing

,Unnamed: 0,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,...,7,0,0,0,0,0,0,3,11,1
1,1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,...,5,0,0,0,0,0,0,3,11,0
2,2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,...,4,0,0,0,0,0,0,3,11,0
3,3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,...,6,0,0,0,0,0,0,3,11,0
4,4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,...,5,0,0,0,0,0,0,3,11,0
2236,2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,...,7,0,0,0,1,0,0,3,11,0
2237,2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,...,6,0,1,0,0,0,0,3,11,0
2238,2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,...,3,0,0,0,0,0,0,3,11,0
2239,2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,...,7,0,0,0,0,0,0,3,11,1

In [4]:
dados_marketing.head(5)

,Unnamed: 0,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,...,7,0,0,0,0,0,0,3,11,1
1,1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,...,5,0,0,0,0,0,0,3,11,0
2,2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,...,4,0,0,0,0,0,0,3,11,0
3,3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,...,6,0,0,0,0,0,0,3,11,0
4,4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,...,5,0,0,0,0,0,0,3,11,0

In [5]:
dados_marketing = dados_marketing[['ID', 'Year_Birth', 'Education', 'Marital_Status', 
                                   'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 
                                   'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [6]:
dados_marketing

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

In [7]:
dados_marketing.head(2).T

                            0           1
ID                       5524        2174
Year_Birth               1957        1954
Education          Graduation  Graduation
Marital_Status         Single      Single
Income                58138.0     46344.0
Kidhome                     0           1
Teenhome                    0           1
Dt_Customer        04-09-2012  08-03-2014
Recency                    58          38
NumStorePurchases           4           2
NumWebVisitsMonth           7           5

In [8]:
dados_marketing.head(3).T

                            0           1           2
ID                       5524        2174        4141
Year_Birth               1957        1954        1965
Education          Graduation  Graduation  Graduation
Marital_Status         Single      Single    Together
Income                58138.0     46344.0     71613.0
Kidhome                     0           1           0
Teenhome                    0           1           0
Dt_Customer        04-09-2012  08-03-2014  21-08-2013
Recency                    58          38          26
NumStorePurchases           4           2          10
NumWebVisitsMonth           7           5           4

In [9]:
dados_marketing.dtypes

ID                     int64
Year_Birth             int64
Education                str
Marital_Status           str
Income               float64
Kidhome                int64
Teenhome               int64
Dt_Customer              str
Recency                int64
NumStorePurchases      int64
NumWebVisitsMonth      int64
dtype: object

In [10]:
dados_marketing.shape

(2240, 11)

In [ ]:
# Agrupamento de Dados

In [11]:
dados_marketing.groupby('Kidhome')['NumStorePurchases'].mean()

Kidhome
0    7.217324
1    3.863181
2    3.437500
Name: NumStorePurchases, dtype: float64

In [ ]:
# para ler mais sobre agrupamento de dados consultar:
# https://www.dataquest.io/blog/grouping-data-a-step-by-step-tutorial-to-groupby-in-pandas/ 
# como forte sugestão sempre consultar o HELP fo fabricante das bibliotecas, ferramentas ou frameworks usados

In [ ]:
#

In [ ]:
# Fusão de Dados (anexação) - neste caso anexamos linhas (as amostras)

In [ ]:
dados_marketing_01 = pd.read_csv("C:/Users/abalb/Desktop/Marketing01_anexar.csv")
dados_marketing_02 = pd.read_csv("C:/Users/abalb/Desktop/Marketing02_anexar.csv")

In [ ]:
dados_marketing_01 = dados_marketing_01[['ID', 'Year_Birth', 'Education', 'Marital_Status', 
                                         'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 
                                         'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [ ]:
dados_marketing_02 = dados_marketing_02[['ID', 'Year_Birth', 'Education', 'Marital_Status', 
                                         'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 
                                         'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [ ]:
dados_marketing_01.shape

In [ ]:
dados_marketing_02.shape

In [ ]:
dados_marketing_01.head()

In [ ]:
dados_marketing_02.head()

In [ ]:
fusao_dados = pd.concat([dados_marketing_01, dados_marketing_02])

In [ ]:
fusao_dados.shape

In [ ]:
fusao_dados.head()

In [ ]:
# Concatenando Dados - neste caso anexar colunas

In [ ]:
dados_marketing_01 = pd.read_csv("C:/Users/abalb/Desktop/Marketing01_Conc.csv")
dados_marketing_02 = pd.read_csv("C:/Users/abalb/Desktop/Marketing02_Conc.csv")

In [ ]:
dados_marketing_01.shape

In [ ]:
dados_marketing_01.head()

In [ ]:
dados_marketing_02.shape

In [ ]:
dados_marketing_02.head()

In [ ]:
dados_concatenados = pd.concat([dados_marketing_01, dados_marketing_02], axis = 1)

In [ ]:
dados_concatenados.shape

In [ ]:
dados_concatenados.head()

In [ ]:
# para ler mais sobre agrupamento de dados consultar:
# https://www.dataquest.io/blog/pandas-concatenation-tutorial/
# como forte sugestão sempre consultar o HELP fo fabricante das bibliotecas, ferramentas ou frameworks usados

In [ ]:
# Mesclando Dados (merge) - realizando uma junção

In [ ]:
dados_marketing_01 = pd.read_csv("C:/Users/abalb/Desktop/Marketing01_Merge.csv")
dados_marketing_02 = pd.read_csv("C:/Users/abalb/Desktop/Marketing02_Merge.csv")

In [ ]:
dados_marketing_01.shape

In [ ]:
dados_marketing_01.head()

In [ ]:
dados_marketing_02.shape

In [ ]:
dados_marketing_02.head()

In [ ]:
dados_mesclados = pd.merge(dados_marketing_01,dados_marketing_02, on = "ID")

In [ ]:
dados_mesclados.shape

In [ ]:
dados_mesclados.head()

In [ ]:
# Ordenando Dados

In [ ]:
dados_marketing = pd.read_csv("C:/Users/abalb/Desktop/Marketing01.csv")

In [ ]:
dados_marketing = dados_marketing[['ID', 'Year_Birth', 'Education', 'Marital_Status', 
                                   'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 
                                   'Recency','NumStorePurchases', 'NumWebVisitsMonth']]

In [ ]:
dados_marketing.head()

In [ ]:
dados_marketing.dtypes

In [ ]:
dados_ordenados = dados_marketing.sort_values('NumStorePurchases', ascending=False)

In [ ]:
dados_ordenados[['ID','NumStorePurchases']]

In [ ]:
# Categorizando Dados

In [ ]:
dados_marketing['bins'] = pd.cut(x = dados_marketing['NumStorePurchases'], bins=[0,4,8,13],
                                 labels = ['Baixa', 'Moderada', 'Alta'])

In [ ]:
dados_marketing[['NumStorePurchases','bins']].head()

In [ ]:
dados_marketing['bins'] = pd.cut(x=dados_marketing['NumStorePurchases'], bins=3, 
                                 labels = ['Baixa', 'Moderada', 'Alta'])

In [ ]:
dados_marketing[['NumStorePurchases','bins']].head()

In [ ]:
# Remoção de Dados Duplicados

In [ ]:
dados_marketing = pd.read_csv("C:/Users/abalb/Desktop/Marketing01.csv")

In [ ]:
dados_marketing = dados_marketing[['Education', 'Marital_Status', 'Kidhome', 'Teenhome']]

In [ ]:
dados_marketing.head()

In [ ]:
dados_marketing.shape

In [ ]:
dados_marketinga_duplicados = dados_marketing.drop_duplicates()

In [ ]:
dados_marketinga_duplicados

In [ ]:
dados_marketinga_duplicados.shape

In [ ]:
# Removendo linhas e colunas de dados

In [ ]:
dados_marketing = pd.read_csv("C:/Users/abalb/Desktop/Marketing01.csv")

In [ ]:
dados_marketing = dados_marketing[['ID', 'Year_Birth', 'Education', 'Marital_Status']]

In [ ]:
dados_marketing = dados_marketing[:5]

In [ ]:
dados_marketing

In [ ]:
dados_marketing.shape

In [ ]:
dados_marketing.drop(labels=[1], axis=0)

In [ ]:
dados_marketing.drop(labels=['Year_Birth'], axis=1)

In [ ]:
# Substituindo dados

In [ ]:
# além da sugestão de consulta ao help deixo como sugestões o acesso:
# https://datatofish.com/replace-values-pandas-dataframe/
# https://www.geeksforgeeks.org/pandas/replace-values-in-pandas-dataframe-using-regex/
# https://www.w3schools.com/python/python_regex.asp

In [ ]:
# Alterar o formato dos dados

In [ ]:
dados_marketing = pd.read_csv("C:/Users/abalb/Desktop/Marketing01.csv")

In [ ]:
dados_marketing = dados_marketing[['ID', 'Year_Birth','Marital_Status','Income']]

In [ ]:
dados_marketing.head()

In [ ]:
dados_marketing.shape

In [ ]:
dados_marketing['Income'] = dados_marketing['Income'].fillna(0)

In [ ]:
dados_marketing['Income_changed'] = dados_marketing['Income'].astype(int)

In [ ]:
dados_marketing[['Income','Income_changed']].head()

In [ ]:
dados_marketing[['Income','Income_changed']].dtypes

In [ ]:
dados_marketing

In [ ]:
# além do help sugiro a seguinte consulta:
# https://pbpython.com/pandas_dtypes.html

In [ ]:
# Alterando Dados

In [ ]:
dados_marketing = pd.read_csv("C:/Users/abalb/Desktop/Marketing01.csv")

In [ ]:
dados_marketing = dados_marketing[['ID', 'Year_Birth', 'Kidhome', 'Teenhome']]

In [ ]:
dados_marketing.head()

In [ ]:
dados_marketing.shape

In [ ]:
dados_marketing['Teenhome_replaced'] = dados_marketing['Teenhome'].replace([0,1,2],['não tem adolescente',
                                                                                    'tem adolescente','tem adolescente'])

In [ ]:
dados_marketing[['Teenhome','Teenhome_replaced']].head()

In [ ]:
# Lidando com Dados Ausentes: uma abordagem inicial

In [ ]:
dados_marketing = pd.read_csv("C:/Users/abalb/Desktop/Marketing01.csv")

In [ ]:
dados_marketing = dados_marketing[['ID', 'Year_Birth', 'Education','Income']]

In [ ]:
dados_marketing.head()

In [ ]:
dados_marketing.shape

In [ ]:
dados_marketing.isnull().sum()

In [ ]:
dados_marketing_sem_NaN = dados_marketing.dropna(how = 'any')
dados_marketing_sem_NaN.head()

In [ ]:
dados_marketing_sem_NaN.shape