# CELULA 01: Importação das bibliotecas
Recupere os microdados e localize o arquivo que contém os resultados individuais de todos os
inscritos no exame. Identifique, através da documentação e do próprio arquivo, as colunas que
trazem os seguintes dados:
1. Notas das provas específicas e notas da redação
2. UF, Cidade e Escola de origem do aluno
3. Tipo de Escola (privada, pública, …)
Faça uma carga parcial do arquivo, tratando apenas dessas colunas. Identifique dados
inconsistentes ou faltantes. Produza dados agregados a partir dos dados brutos:
a) Média de notas por aluno
b) Média de notas por escola
c) Média de notas por município
d) Média de notas por UF
Produza um ranking dos 10 melhores alunos, 10 melhores escolas (geral e nos extratos
públicos e privado) e 10 melhores municípios do país e do Rio Grande do Sul.

# CELULA 01: Importação das bibliotecas
Nesta etapa serão importadas as bibliotecas Pandas e NumPy para tratamento dos dados.

In [1]:
import pandas as pd
import numpy as np

# CELULA 02: Leitura parcial dos microdados
Como os microdados do ENEM possuem tamanho elevado, será feita uma leitura parcial das colunas necessárias.
Essas colunas atendem ao núcleo do projeto: notas específicas, redação, UF, município e tipo de escola. A parte “cidade e escola de origem” pode exigir cuidado, porque em algumas versões dos microdados há restrições/supressões por LGPD; o próprio INEP informa que os formatos dos microdados vêm sendo reestruturados para reduzir possibilidade de identificação de pessoas.

Criamos as variaveis 'coluna=' e 'caminho=' para simplificas a sintaxe, quando usar nos comandos

In [3]:
caminho = "C:/Users/enggi/IA_CURSO/ALGORITMO PROGRAMACAO APE/AULA06/RESULTADOS_2024.csv"
colunas_resul = [
    # identificação
    "NU_SEQUENCIAL",  # numero da inscrição do aluno.

    # localização do participante
    "SG_UF_ESC",          # Sigla da UF onde foi a prova 
    "NO_MUNICIPIO_ESC",   # Nome da cidade onde foi a prova

    # escola
    "TP_DEPENDENCIA_ADM_ESC",     # Codigo tipo de escola 1=Federal, 2=Estadual, 3=Municipal, 4=Privada
    "CO_ESCOLA",                   # Codigo da escola

    # notas das provas objetivas
    "NU_NOTA_CN",   # nota Ciencias Naturais
    "NU_NOTA_CH",   # nota Ciencias Humanas 
    "NU_NOTA_LC",   # nota Linguagem e Codigo
    "NU_NOTA_MT",   # nota Matematica 

    # nota da redação
    "NU_NOTA_REDACAO" # Nota da redação
]
# Especificar o tipo de numero para ecomizar memória, float32 usa 16bytes.
dtypes_resul = {
    'NU_NOTA_CN': 'float32',
    'NU_NOTA_CH': 'float32',
    'NU_NOTA_LC': 'float32',
    'NU_NOTA_MT': 'float32',
}
df = pd.read_csv(
    caminho,
    sep=";",               #porque os microdados geralmente usam ponto e vírgula;
    encoding="latin1",     #Para não gerar erros devido a acentuação
    usecols=colunas_resul, #carrega só as colunas necessárias;
    dtype=dtypes_resul,    # Type numerico
    nrows=100_000          #carrega apenas as primeiras 100 mil linhas para teste.
)

df.head()

,NU_SEQUENCIAL,CO_ESCOLA,NO_MUNICIPIO_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,206403,23052929.0,Aratuba,CE,2.0,436.799988,377.799988,423.399994,427.100006,300.0
1,3604651,42103770.0,Tijucas,SC,4.0,521.900024,601.900024,605.500000,689.200012,920.0
2,1461268,NaN,NaN,NaN,NaN,363.000000,548.400024,557.200012,456.399994,480.0
3,4301058,NaN,NaN,NaN,NaN,550.700012,553.799988,605.900024,629.099976,740.0
4,3148322,21150354.0,Alto Alegre do Maranhão,MA,2.0,NaN,NaN,NaN,NaN,NaN

# CELULA 03
Verificação de dados faltantes

In [4]:
df.info()
df.isnull().sum()
df.isnull().mean() * 100

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   NU_SEQUENCIAL           100000 non-null  int64
 1   CO_ESCOLA               36232 non-null   float64
 2   NO_MUNICIPIO_ESC        36232 non-null   str
 3   SG_UF_ESC               36232 non-null   str
 4   TP_DEPENDENCIA_ADM_ESC  36232 non-null   float64
 5   NU_NOTA_CN              69121 non-null   float32
 6   NU_NOTA_CH              73025 non-null   float32
 7   NU_NOTA_LC              73025 non-null   float32
 8   NU_NOTA_MT              69121 non-null   float32
 9   NU_NOTA_REDACAO         73025 non-null   float64
dtypes: float32(4), float64(3), int64(1), str(2)
memory usage: 6.1 MB

NU_SEQUENCIAL              0.000
CO_ESCOLA                 63.768
NO_MUNICIPIO_ESC          63.768
SG_UF_ESC                 63.768
TP_DEPENDENCIA_ADM_ESC    63.768
NU_NOTA_CN                30.879
NU_NOTA_CH                26.975
NU_NOTA_LC                26.975
NU_NOTA_MT                30.879
NU_NOTA_REDACAO           26.975
dtype: float64

# CELULA 04 
Ver em porcentagem os dados faltantes

In [5]:
faltantes_percentual = df.isnull().mean() * 100
faltantes_percentual.round(2)

NU_SEQUENCIAL              0.00
CO_ESCOLA                 63.77
NO_MUNICIPIO_ESC          63.77
SG_UF_ESC                 63.77
TP_DEPENDENCIA_ADM_ESC    63.77
NU_NOTA_CN                30.88
NU_NOTA_CH                26.98
NU_NOTA_LC                26.98
NU_NOTA_MT                30.88
NU_NOTA_REDACAO           26.98
dtype: float64

# CELULA 05 - Criar média por aluno
Cria uma lista chamada 'colunas_notas' contendo os nomes das colunas
que armazenam as notas do ENEM.
Essas colunas serão usadas para calcular a média de cada aluno.

In [10]:
colunas_notas = [
    "NU_NOTA_CN",       # Nota de Ciências da Natureza
    "NU_NOTA_CH",       # Nota de Ciências Humanas
    "NU_NOTA_LC",       # Nota de Linguagens e Códigos
    "NU_NOTA_MT",       # Nota de Matemática
    "NU_NOTA_REDACAO"   # Nota da Redação
]

df["MEDIA_ALUNO"] = df[colunas_notas].mean(axis=1)
#Cria uma nova coluna no DataFrame chamada "MEDIA_ALUNO".
# Para cada linha, ou seja, para cada aluno, calcula a média das notas
# presentes nas colunas listadas em 'colunas_notas'.
#
# df[colunas_notas] seleciona apenas as colunas de notas.
# .mean(axis=1) calcula a média na direção das colunas, isto é, calcula uma média por aluno.


df[["NU_SEQUENCIAL", "MEDIA_ALUNO"]].head()
#Seleciona apenas as colunas "NU_INSCRICAO" e "MEDIA_ALUNO" e mostra as 5 primeiras linhas com o método head().

   NU_SEQUENCIAL  MEDIA_ALUNO
0         206403   393.019995
1        3604651   667.700012
2        1461268   481.000006
3        4301058   615.900000
4        3148322          NaN

# CELULA 06 - Ranking dos 10 melhores alunos
Crio a variavel 'ranking_alunos=', comando 'df.sort_values é um método do Pandas para Ordenar o DataFrame com base na coluna "MEDIA_ALUNO".
O parâmetro by="MEDIA_ALUNO" indica que a ordenação será feita pela média dos alunos.
O parâmetro ascending=False indica ordem decrescente, ou seja,
os alunos com maiores médias aparecem primeiro.
O método .head(10) seleciona apenas os 10 primeiros registros após a ordenação.

In [ ]:
ranking_alunos = df.sort_values(
    by="MEDIA_ALUNO",
    ascending=False
).head(10)

print("Ranking dos 10 melhores alunos:")
ranking_alunos[
    [
        "NU_SEQUENCIAL", 
        "SG_UF_ESC", 
        "NO_MUNICIPIO_ESC", 
        "TP_DEPENDENCIA_ADM_ESC", 
        "MEDIA_ALUNO"
    ]
]

Ranking dos 10 melhores alunos:

,NU_SEQUENCIAL,SG_UF_ESC,NO_MUNICIPIO_ESC,TP_DEPENDENCIA_ADM_ESC,MEDIA_ALUNO
48847,410981,CE,Fortaleza,4.0,825.940002
59347,2174880,NaN,NaN,NaN,822.080005
34289,833685,NaN,NaN,NaN,820.619995
65605,2740037,NaN,NaN,NaN,817.260010
84687,1386260,NaN,NaN,NaN,817.199988
54615,103204,NaN,NaN,NaN,816.500012
63509,3430345,NaN,NaN,NaN,816.000000
18278,820758,NaN,NaN,NaN,815.019995
90921,82460,NaN,NaN,NaN,814.620007
30817,248857,NaN,NaN,NaN,812.379993